# Adding Resource Use to Vidigi Animations

To recap, we're going to

1. swap in a *custom* resource class instead of Simpy.Resource
1. capture the ID of the resource used
1. swap the logging type for resource use events and store this resource ID
1. pass our params class to our animation (so it knows how many resources there are) and our event position dataframe.

## 1a. Import the new resource class

First, we need to make sure we have imported our new class.

::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```python
from vidigi.resources import VidigiStore
```
:::

::: {style="display: flex; justify-content: center; align-items: center;"}

::: {.value-box value="Note" icon="fa-solid fa-lightbulb" icon-position="left" align="center" color="bg-green"}
We *could* instead use

`import vidigi`

And then

`vidigi.resources.VidigiStore`

whenever we want to use it, but the vidigi documentation uses the convention detailed above
:::


:::



## 1b. Swap in the new resource class instead of Simpy.Resource

:::: {.columns}

::: {.column width='10%'}
::: {style='font-size: 55%;'}
**Before**
:::
:::

::: {.column width='90%'}
::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-3,focus:4" code-line-style-preset="emphasis"}
class Model:
    def __init__(self, param):
        ...
        self.nurse = simpy.Resource(self.env, capacity=self.param.num_nurses)
```
:::
:::

::::



:::: {.columns}

::: {.column width='10%'}
::: {style='font-size: 55%;'}
**After**
:::
:::

::: {.column width='90%'}
::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="dim:1-3,focus:4" code-line-style-preset="emphasis"}
class Model:
    def __init__(self, param):
        ...
        self.nurse = VidigiStore(self.env, num_resources=self.param.num_nurses) # UPDATED
```
:::
:::

::::

::: {style='font-size: 75%;'}
- We change `simpy.Resource` to `VidigiStore`
- We change 'capacity' to 'num_resources' (as capacity has its own special meaning in vidigi's resources)
:::

## 2. Capture the ID of the resource

:::: {.columns}

::: {.column width='20%'}
**Before**
:::

::: {.column width='80%'}
::: {style='font-size: 75%;'}
::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-4,focus:5-6" code-line-style-preset="emphasis"}
def attend_clinic(self, patient):
        ...
        self.logger.log_queue(entity_id=patient.id, event="nurse_wait_begins")

        with self.nurse.request() as req:
            yield req
```
:::
:::
:::

::::

:::: {.columns}

::: {.column width='15%'}
**After**
:::

::: {.column width='85%'}
::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="dim:1-4,focus:5-6" code-line-style-preset="emphasis"}
def attend_clinic(self, patient):
        ...
        self.logger.log_queue(entity_id=patient.id, event="nurse_wait_begins")

        with self.nurse.request() as req:
            nurse_obtained = yield req # UPDATED
```
:::
:::

::::


::: {style="font-size: 70%;"}

We need to assign the result of this yield to a variable. We'll then be able to extract the resource ID for logging.

We can call it anything, but make sure you don't name it the exact same thing as your resource!

:::

## 3a. Swap the logging type

we will swap the logging type from `log_queue` to `log_resource_use_start` and `log_resource_use_end`

These methods accept an extra parameter - `resource_id`.

:::: {.columns}

::: {.column width='40%'}
**Before**

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python}
self.logger.log_queue(
    entity_id=patient.id,
    event="being_seen_by_nurse"
)
```
:::
:::

::: {.column width='60%'}
**After**

::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="focus:1,dim:2-3,focus:4,dim:5" code-line-style-preset="emphasis"}
self.logger.log_resource_use_start( # UPDATED
    entity_id=patient.id,
    event="being_seen_by_nurse",
    resource_id=nurse_obtained.id_attribute,  # NEW
)
```
:::
:::

::::

The variable we assigned to is a VidigiResource object behind the scenes, and that has a special `id_attribute` we can access that contains a unique identifier for that resource.

## 3b. Repeat this for when they finish with the resource

Just before the end of the indented nurse block, we do this to record in our event log that the resource  became free at that point.

:::: {.columns}

::: {.column width='40%'}
**Before**

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python}
self.logger.log_queue(
    entity_id=patient.id,
    event="nurse_treatment_ends"
)
```
:::

:::

::: {.column width='60%'}
**After**

::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="focus:1,dim:2-3,focus:4,dim:5" code-line-style-preset="emphasis"}
self.logger.log_resource_use_end( # UPDATED
    entity_id=patient.id,
    event="nurse_treatment_ends",
    resource_id=nurse_obtained.id_attribute,  # NEW
)
```
:::

:::

::::


## SUMMARY: our full revised `attend_clinic()` method

::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="dim:1-6,focus:7,dim:8-11,focus:12-15,dim:16-19,focus:20-23,dim:24-25" code-line-style-preset="emphasis"}
def attend_clinic(self, patient):
    self.logger.log_arrival(entity_id=patient.id)
    start_q_nurse = self.env.now
    self.logger.log_queue(entity_id=patient.id, event="nurse_wait_begins")

    with self.nurse.request() as req:
        nurse_obtained = yield req # UPDATED

        end_q_nurse = self.env.now
        patient.q_time_nurse = end_q_nurse - start_q_nurse

        self.logger.log_resource_use_start( # UPDATED
            entity_id=patient.id, event="being_seen_by_nurse",
            resource_id=nurse_obtained.id_attribute, # NEW
        )

        sampled_nurse_act_time = self.nurse_consult_time_dist.sample()
        yield self.env.timeout(sampled_nurse_act_time)

        self.logger.log_resource_use_end( # UPDATED
            entity_id=patient.id, event="nurse_treatment_ends",
            resource_id=nurse_obtained.id_attribute # NEW
            )

    self.logger.log_departure(entity_id=patient.id)
```
:::

## 4. Pass our params class to our animation class...

::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="dim:1,focus:2,dim:3,focus:4" code-line-style-preset="emphasis"}
class Animation:
    def __init__(self, event_log, params):  # UPDATED
        self.event_log = event_log
        self.params = params  # NEW
```
:::

## 4b. ... our event position df...

::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="dim:1-3,focus:4-7,dim:8" code-line-style-preset="emphasis"}
self.layout = create_event_position_df(
    [EventPosition(event="arrival", x=0, y=350, label="Entrance"),
     EventPosition(event="nurse_wait_begins", x=200, y=250, label="Waiting for Nurse"),
     EventPosition(
        event="being_seen_by_nurse", x=200, y=150, label="Being Seen By Nurse",
        resource="num_nurses", # NEW
    ),
    EventPosition(event="depart", x=200, y=50, label="Exit")])
```
:::

:::: {.columns}

::: {.column width='35%'}
::: {style='font-size: 70%;'}
When we pass the resource name, this will be looked up from our Params class, so we need to make sure the name exactly matches how it's written there

We **still** don't need to visualise the 'nurse_treatment_ends' step!
:::
:::

::: {.column width='65%'}
::: {style='font-size: 90%;'}
::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="focus:1,dim:2-7,focus:8,dim:9-10" code-line-style-preset="emphasis"}
class Param:
  def __init__(
      self, ...
      sd_nurse_consult_time=1, num_nurses=1, sim_duration=120, ...
  ):
      ...
      self.sd_nurse_consult_time = sd_nurse_consult_time
      self.num_nurses = num_nurses
      self.sim_duration = sim_duration
      ...
```
:::
:::
:::

::::




## 4c. ... and our animation method...

::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="dim:1-5,focus:6,dim:7" code-line-style-preset="emphasis"}
def build_animation(self, time_interval=1):
    return animate_activity_log(
        event_log=self.event_log,
        event_position_df=self.layout,
        every_x_time_units=time_interval,
        scenario=self.params,  # NEW
    )
```
:::


## 4d. ... and when we create our instance of the animation class

::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="focus:1,dim:2-3,focus:4,dim:5,focus:5-8" code-line-style-preset="emphasis"}
my_params = Param(num_nurses=2)
my_model = Model(my_params)
my_model.run_model()
my_event_log = my_model.get_vidigi_event_log()

my_animation = Animation(
    my_event_log,
    my_params # NEW
    )
```
:::


## The event log

::: {style='font-size: 75%;'}
Our event log now has a new `resource_id` column.
:::



```{python}
#| eval: true
#| echo: false
#| label: resource-model-animate-display-event-log

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(os.environ["QUARTO_PROJECT_DIR"])

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import itables
import pandas as pd
from IPython.display import HTML
itables.init_notebook_mode(all_interactive=True)
itables.options.lengthMenu = [10]
itables.options.layout["topStart"] = None
display(HTML("<style>.dt-container { font-size: 20pt; }</style>"))

from sample_code.c_simple_one_step_model_vidigi_resources import Param, Model, Animation
from vidigi.animation import animate_activity_log

my_params = Param(num_nurses=2)
my_model = Model(my_params)
my_model.run_model()

my_event_log = my_model.get_vidigi_event_log()

my_event_log
```


## The animation

```{python}
#| eval: true
#| echo: false
#| label: resource-model-animate-display-animation

my_animation = Animation(my_event_log, my_params)

fig = animate_activity_log(
    event_log=my_animation.event_log,
    event_position_df=my_animation.layout,
    every_x_time_units=1,
    plotly_height=600,
    plotly_width=1180,
    scenario=my_params
)

HTML(fig.to_html(full_html=False, include_plotlyjs="cdn", auto_play=False))
```


## Custom Resource Icons

Optionally, we could use a **custom resource icon** rather than the default blue circle.

```{.python code-line-style="dim:1-8,focus:9-10,dim:11" code-line-style-preset="emphasis"}
class Animation:
    ...
    def build_animation(self, time_interval=1):
        return animate_activity_log(
            event_log=self.event_log,
            event_position_df=self.layout,
            every_x_time_units=time_interval,
            scenario=self.params,
            custom_resource_icon="👩‍⚕️",  # NEW - note the quotation marks!
            resource_icon_size=32,  # NEW
        )
```

## What custom Resource Icons can we use?

At the moment, vidigi supports **emojis**.

Yep - that kind of emoji.

::: {style='font-size: 150%;'}
😁 🤣 😉 🤪 🫠 😭 😱
:::

But there are also quite a lot of relevant ones.

::: {style='font-size: 150%;'}
👩‍⚕️ 👨🏿‍⚕️ 🛏️ 🏥 🚑
:::

I find the best place to look them up and copy them in is [emojipedia.org](https://emojipedia.org/)


## The Revised Animation - Custom Resource Icons

```{python}
#| eval: true
#| echo: false
#| label: resource-model-custom-resource-icons
fig = animate_activity_log(
    event_log=my_animation.event_log,
    event_position_df=my_animation.layout,
    every_x_time_units=1,
    plotly_height=600,
    plotly_width=1180,
    scenario=my_params,
    custom_resource_icon="👩‍⚕️",
    resource_icon_size=32,
    entity_icon_size=40
)

HTML(fig.to_html(full_html=False, include_plotlyjs="cdn", auto_play=False))
```


## Custom Entity Icons

In fact, we can change the list of valid emojis for our patients too!

```{.python code-line-style="dim:1-8,focus:9,dim:10" code-line-style-preset="emphasis"}
class Animation:
    ...
    def build_animation(self, time_interval=1):
        return animate_activity_log(
            event_log=self.event_log,
            event_position_df=self.layout,
            every_x_time_units=time_interval,
            scenario=self.params,
            custom_entity_icon_list=["🤢", "🤒", "🤧", "😷"]
        )
```

::: {style='font-size: 85%;'}
Later, we'll learn how to intelligently assign these to different types of patient...

But sometimes you just want to change the default list, or just want every entity to have the same icon, in which case, you can pass a list with just one emoji in it.
:::


## The Revised Animation - Custom Entity Emojis

```{python}
#| eval: true
#| echo: false
#| label: resource-model-custom-entity-emojis
fig = animate_activity_log(
    event_log=my_animation.event_log,
    event_position_df=my_animation.layout,
    every_x_time_units=1,
    plotly_height=600,
    plotly_width=1180,
    scenario=my_params,
    custom_entity_icon_list=["🤢", "🤒", "🤧", "😷"]
)

HTML(fig.to_html(full_html=False, include_plotlyjs="cdn", auto_play=False))
```
