# Incorporating the Trial Class

## Trial, trial again

So far we've been working with a vidigi model that only runs a single replication.

However, we saw in earlier sessions how important it is to run **multiple replications** in simulation.

So how can we make vidigi play nicely with the trial class?

## Recapping the Trial Class

::: {.codewindow .python}
d_simple_one_step_model_vidigi_trial.py
```{.python code-line-style="|focus:2-7|focus:9-17|focus:19-31" code-line-style-preset="emphasis"}
class Trial:
    def __init__(self, param):
        self.param = param
        self.list_of_simulation_replications = []
        self.trial_mean_q_time_nurse = pd.NA
        self.trial_sd_q_time_nurse = pd.NA
        self.trial_perc_90_q_time_nurse = pd.NA

    def run_trial(self):
        for replication_id in range(self.param.num_replications):
            model_replication = Model(self.param)
            model_replication.run_model()
            patient_df = model_replication.convert_entity_list_to_dataframe(
                model_replication.list_of_patients
            )
            model_replication.calculate_run_results(patient_df)
            self.list_of_simulation_replications.append(model_replication)

    def calculate_trial_results(self):
        self.replication_df = pd.DataFrame(
            replication.__dict__ for replication in self.list_of_simulation_replications
        )

        self.trial_mean_q_time_nurse = self.replication_df["mean_q_time_nurse"].mean()

        self.trial_sd_q_time_nurse = self.replication_df["mean_q_time_nurse"].std()

        self.trial_perc_90_q_time_nurse = self.replication_df[
            "mean_q_time_nurse"
        ].quantile(0.9)
```
:::

## Tracking Replications - Tweaking the Model Class

Vidigi works best if it knows what run a trial came from.

So first (if we haven't already - if you're following best practice, you'll have that!), we're going to go and tweak our `Model` class to store the run number and pass it to our EventLogger.

::: {.codewindow .python}
d_simple_one_step_model_vidigi_trial.py
```{.python code-line-style="dim:1,focus:2,dim:3,focus:4,dim:5-6,focus:9" code-line-style-preset="emphasis"}
class Model:
    def __init__(self, param, replication_id):  # UPDATED
        self.param = param
        self.replication_id = replication_id  # NEW
        self.env = simpy.Environment()
        self.patient_counter = 0
        self.logger = EventLogger(
            env=self.env,
            run_number=self.replication_id,  # UPDATED
        )
```
:::

## Tracking Replications - Adding a new import

We're going to be making use of Vidigi's `TrialLogger` class. This takes multiple EventLogger objects and allows us to do fancy things with them!

:::: {.columns}

::: {.column width='40%'}
::: {style='font-size: 85%;'}
First, we update our import statement.
:::
:::

::: {.column width='60%'}
::: {style='font-size: 85%;'}
```{.python}
from vidigi.logging import EventLogger, TrialLogger # UPDATED
```
:::
:::

::::

:::: {.columns}

::: {.column width='40%'}
::: {style='font-size: 80%;'}
Next, we need to update our `__init__` method to set up an attribute to store this object in.

We initialise an empty TrialLogger so we can add our EventLogger objects to it as we go.
:::
:::

::: {.column width='60%'}
::: {.codewindow .python}
d_simple_one_step_model_vidigi_trial.py
```{.python code-line-style="dim:3-7,focus:8" code-line-style-preset="emphasis"}
class Trial:
    def __init__(self, param):
        self.param = param
        self.list_of_simulation_replications = []
        self.trial_mean_q_time_nurse = pd.NA
        self.trial_sd_q_time_nurse = pd.NA
        self.trial_perc_90_q_time_nurse = pd.NA
        self.trial_logger = TrialLogger()  # NEW
```
:::
:::

::::

## Tracking Replications - Tweaking the Trial Class

We now just pass our replication_id into the model in the `run_trial()` method (again - this part might already have been done in your model).

We then add our log to the `trial_logger` in every round of the loop.

:::: {.columns}

::: {.column width='80%'}
::: {.codewindow .python}
d_simple_one_step_model_vidigi_trial.py
```{.python code-line-style="focus:3,dim:4-9,focus:10" code-line-style-preset="emphasis"}
def run_trial(self):
    for replication_id in range(self.param.num_replications):
        model_replication = Model(self.param, replication_id) # UPDATED
        model_replication.run_model()
        patient_df = model_replication.convert_entity_list_to_dataframe(
            model_replication.list_of_patients
        )
        model_replication.calculate_run_results(patient_df)
        self.list_of_simulation_replications.append(model_replication)
        self.trial_logger.add_log(model_replication.logger) # NEW
```
:::

:::

::: {.column width='20%'}
::: {.value-box fragment="fade-in" icon="fa-solid fa-triangle-exclamation" icon-position="top" align="center" color="bg-amber" font-size=0.9rem}
Note that the replication_id will count from 0
:::
:::

::::


## Animating a run from the TrialLogger

::: {style='font-size: 75%;'}
Now we need to update our animation code to animate a single run.

`TrialLogger` has its own `animate_activity_log()` method, just like the `EventLogger` does. It takes all the same arguments, plus a `run_number` to say which replication we want to animate.
:::

:::: {.columns}

::: {.column width='15%'}
**Before**
:::

::: {.column width='85%'}
::: {.codewindow .python}
c_simple_one_step_model_vidigi_resources.py
```{.python code-line-style="focus:1,dim:2-5" code-line-style-preset="emphasis"}
fig = my_model.logger.animate_activity_log(
    event_position_df=layout, every_x_time_units=1, scenario=my_params,
)
```
:::
:::

::::

:::: {.columns}

::: {.column width='15%'}
**After**
:::

::: {.column width='85%'}
::: {.codewindow .python}
d_simple_one_step_model_vidigi_trial.py
```{.python code-line-style="focus:1-2,dim:3-6" code-line-style-preset="emphasis"}
fig = my_trial.trial_logger.animate_activity_log(
    run_number=1,  # NEW
    event_position_df=layout, every_x_time_units=1, scenario=my_params,
)
```
:::
:::

::::

::: {.value-box icon="fa-solid fa-lightbulb" icon-position="left" align="center" color="bg-green"}
Now we can regenerate the animation for different runs by just changing what we pass to `run_number`!
:::

## Getting a run's event log from the TrialLogger

`TrialLogger` also provides a useful helper method called `.get_log_by_run()`, for when we want to look at the event log for a particular run.

We can pass in any run number, and also choose whether it should be returned as an `EventLogger` object, or as a dataframe.

::: {.codewindow .python}
d_simple_one_step_model_vidigi_trial.py
```{.python}
print(my_trial.trial_logger.get_log_by_run(run=1, as_df=True).head(10))
```
:::

```{python}
#| eval: true
#| echo: false
#| label: initiate-trial-example
from sample_code.d_simple_one_step_model_vidigi_trial import Param, Trial

my_params = Param(mean_patient_inter=3, num_nurses=2, mean_nurse_consult_time=10, num_replications=10)
my_trial = Trial(my_params)
my_trial.run_trial()
my_trial.calculate_trial_results()

import plotly.io as pio
pio.renderers.default = "notebook"
```

## Summary: Changes for animations with the Trial class {style='font-size: 72%;'}

:::: {.columns}

::: {.column width='30%'}

Ensure you're tracking the `replication_id` in your `Model` class and pass this to the `EventLogger`

:::

::: {.column width='70%'}
```{.python code-line-style="focus:2,dim:3,focus:4,dim:5,focus:8,dim:9" code-line-style-preset="emphasis"}
class Model:
    def __init__(self, param, replication_id):  # UPDATED
        self.param = param
        self.replication_id = replication_id  # NEW
        ...
        self.logger = EventLogger(
            env=self.env,
            run_number=self.replication_id,  # UPDATED
        )
```
:::

::::

:::: {.columns .fragment}

::: {.column width='30%'}
Import TrialLogger
:::

::: {.column width='70%'}
```{.python}
from vidigi.logging import EventLogger, TrialLogger # UPDATED
```
:::

::::

:::: {.columns .fragment}

::: {.column width='30%'}
Initialise the `TrialLogger` in the `Trial` class.
:::

::: {.column width='70%'}
```{.python code-line-style="dim:3" code-line-style-preset="emphasis"}
class Trial:
    def __init__(self, param):
        ...
        self.trial_logger = TrialLogger()  # NEW
```
:::

::::


:::: {.columns .fragment}

::: {.column width='30%'}
Update the `run_trial` method to save each `EventLogger` to the `TrialLogger`
:::

::: {.column width='70%'}
```{.python code-line-style="dim:2,focus:5,dim:6-7,focus:8" code-line-style-preset="emphasis"}
class Trial:
    ...
    def run_trial(self):
        for replication_id in range(self.param.num_replications):
            model_replication = Model(self.param, replication_id) # UPDATED
            model_replication.run_model()
            ...
            self.trial_logger.add_log(model_replication.logger) # NEW
```
:::


::::

:::: {.columns .fragment}

::: {.column width='30%'}
Animate from the `TrialLogger`, choosing a `run_number`
:::

::: {.column width='70%'}
```{.python code-line-style="focus:1-2,dim:3-6" code-line-style-preset="emphasis"}
fig = my_trial.trial_logger.animate_activity_log( # UPDATED
    run_number=1,  # NEW
    event_position_df=layout,
    every_x_time_units=1,
    scenario=my_params,
)
```
:::

::::
