

# Statistics and Plots from TrialLogger and EventLogger

```{python}
#| eval: true
#| echo: false
#| label: initiate-trial-example-trial-logger-viz-demo
from sample_code.d_simple_one_step_model_vidigi_trial import Param, Trial
from IPython.display import HTML

my_params = Param(mean_patient_inter=3, num_nurses=2, mean_nurse_consult_time=10, num_replications=10)
my_trial = Trial(my_params)
my_trial.run_trial()
my_trial.calculate_trial_results()

import plotly.io as pio
pio.renderers.default = "notebook"
```

## BONUS!

`TrialLogger` and `EventLogger` both have a range of built-in useful helper functions and plots.

<br>

::: {.value-box fragment="fade-in" icon="fa-solid fa-lightbulb" icon-position="left" align="center" color="bg-green" value="Why use these rather than making my own plots?" width="95%"}

<br>

There's nothing to stop you still making your own plots - and I'd actively encourage it!

But vidigi's plots have the benefit of being part of a tested ecosystem.

They will also hopefully save you time!
:::

## TrialLogger - Average durations

With `.get_event_duration_stat()`, we can easily pull out average durations for across the whole trial.

:::: {.columns}

::: {.column width='30%'}
**For every entity**
:::

::: {.column width='70%'}
```{python}
#| eval: true
#| echo: true
#| label: trial-logger-event-duration_stat_mean
my_trial.trial_logger.get_event_duration_stat(
    first_event="nurse_wait_begins",
    second_event="being_seen_by_nurse",
    what="mean",
    exclude_incomplete=True,
    across="entities"
    )
```
:::

::::

::: {style='font-size: 35%;'}
<br>
:::

:::: {.columns}

::: {.column width='30%'}
**Per Run, Averaged**
:::

::: {.column width='70%'}
```{python}
#| eval: true
#| echo: true
#| label: trial-logger-event-duration_stat_median
my_trial.trial_logger.get_event_duration_stat(
    first_event="nurse_wait_begins",
    second_event="being_seen_by_nurse",
    what="mean",
    exclude_incomplete=True,
    across="runs"
    )
```
:::

::::








## TrialLogger - Duration Barplot

::: {style='font-size: 80%;'}
We can also look at this as a plot for multiple events at once.
:::

:::: {.columns}

::: {.column width='30%'}
First, we define our 'pairs' of events and give them some nicer names.
:::

::: {.column width='70%'}
```{python}
#| eval: true
#| echo: true
#| label: trial-logger-event-pairs
event_pairs = [
        {"first_event": "nurse_wait_begins",
         "second_event":"being_seen_by_nurse",
         "label": "Nurse Wait Length"},
         {"first_event": "being_seen_by_nurse",
         "second_event":"nurse_treatment_ends",
         "label": "Nurse Treatment Length"},
         {"first_event": "arrival",
         "second_event":"depart",
         "label": "Full Journey Duration"},
]
```
:::

::::

::: {style='font-size: 80%;'}
Note that we're finally getting a chance to use that "nurse_treatment_ends" activity!

While it's still identically timed to *depart* here

- it is more intuitive to make use of it
- it avoids issues if we add more steps to our process down the line
:::


## TrialLogger - Duration Barplot - Output

:::: {.columns}

::: {.column width='50%'}
This then gives us a good overview of the time entities are spending queueing for each step.
:::

::: {.column width='50%'}
```{python}
#| eval: true
#| echo: true
#| label: trial-logger-event-duration-barplot
my_trial.trial_logger.plot_metric(
    event_pairs, what="mean",
    kind="bar",
    )
```

:::

::::


## Using TrialLogger Plots to Understand Variation

::: {style='font-size: 75%;'}
But by using box and bar plots with `across=runs`, we can see how this varied.
:::

:::: {.columns}

::: {.column width='50%'}

::: {style='font-size: 75%;'}
```{python}
#| eval: true
#| echo: true
#| label: trial-logger-event-duration-box
my_trial.trial_logger.plot_metric(
    event_pairs, what="mean",
    kind="box", across="runs", show_runs=True
  )
```
:::

:::

::: {.column width='50%'}
::: {style='font-size: 75%;'}
```{python}
#| eval: true
#| echo: true
#| label: trial-logger-event-duration-violin
my_trial.trial_logger.plot_metric(
    event_pairs, what="mean",
    kind="violin", across="runs", show_runs=True
  )
```
:::
:::
::::


##


:::: {.columns}

::: {.column width='50%'}
Or we can add confidence intervals to our original barplot
:::

::: {.column width='50%'}
```{python}
#| eval: true
#| echo: true
#| label: trial-logger-event-duration-barplot-ci
my_trial.trial_logger.plot_metric(
    event_pairs, what="mean",
    kind="bar", across="runs",
    error_bars="ci"
    )
```
:::

::::

## TrialLogger - Queue length

:::: {.columns}

::: {.column width='25%'}
::: {style='font-size: 75%;'}
`.plot_queue_size` allows us to see how queues changed across the course of our model run, for every run.

The black line indicates the average queue size, while the coloured lines show how the queue varied across runs.
:::
:::

::: {.column width='75%'}
```{python}
#| eval: true
#| echo: true
#| label: trial-logger-queue-length
my_trial.trial_logger.plot_queue_size(
    ["nurse_wait_begins"],
    limit_duration=my_params.sim_duration,
    every_x_time_units=30, title="Nurse Queue Length",
    width=875, height=450)
```
:::

::::

## And more!

::: {style='font-size: 75%;'}
There are lots more plots within vidigi, including plots that can compare outputs from multiple runs.

You'll explore more plots in the exercise, and can find out about them all in the API reference (below) and [TrialLogger page](https://hsma-tools.github.io/vidigi/examples/feat_trial_logger/feat_trial_logger.html).
:::


```{=html}
<iframe width='1200' height='600' src='https://hsma-tools.github.io/vidigi/reference/#analysis-plots' title='Vidigi Plot documentation'></iframe>
```


## Modifying these plots

Vidigi uses 'Plotly' throughout for its plots - which you've already had some experience with.

The Plotly objects returned can be further modified if there is something you don't like about them or if they don't provide all of the options you need.

To do this, we first need to assign the plot to a variable so we can keep accessing it.

```{.python code-line-style="focus:1,dim:2-6" code-line-style-preset="emphasis"}
fig = my_trial.trial_logger.plot_queue_size(
    ["nurse_wait_begins"],
    limit_duration=my_params.sim_duration,
    every_x_time_units=30, title="Nurse Queue Length",
    width=1000, height=400
    )
```


## Modifying these plots (continued)

::::: {style='font-size: 80%;'}

:::: {.columns}

::: {.column width='30%'}
We can update something that already exists like the axis labels

:::

::: {.column width='70%'}
```{.python}
fig = my_trial.trial_logger.plot_queue_size(...)

fig.update_xaxes(title_text="Simulation time (minutes)")
fig.update_yaxes(title_text="People waiting")
```
:::

::::


:::: {.columns}

::: {.column width='30%'}
Or adjust the layout - here we are reducing the margins

:::

::: {.column width='70%'}
```{.python}
fig.update_layout(margin=dict(l=20,r=20,t=40,b=20))
```

:::

::::

:::: {.columns}

::: {.column width='30%'}
Or add something completely new, like a horizontal reference line

:::

::: {.column width='70%'}
```{.python}
fig.add_hline(
    y=10, line_dash="dash",
    annotation_position="top left",
    annotation_text="Target max queue length"
    )
```
:::

::::

:::::


## Modifying these plots - output

:::: {.columns}

::: {.column width='50%'}
We will need to use `.show()` to make the plot display.
:::

::: {.column width='50%'}
```{.python}
fig.show()
```
:::

::::


```{python}
#| eval: true
#| echo: false
#| label: trial-logger-queue-length-edited
fig = my_trial.trial_logger.plot_queue_size(
    ["nurse_wait_begins"], limit_duration=my_params.sim_duration,
    every_x_time_units=30, title="Nurse Queue Length",
    width=1000, height=550)

# Change the axis labels
fig.update_xaxes(title_text="Simulation time (minutes)")
fig.update_yaxes(title_text="People waiting")

# Add a horizontal reference line
fig.add_hline(
    y=10, line_dash="dash",
    annotation_text="Target max queue length",
    annotation_position="top left"
)

fig.update_layout(
margin=dict(
        l=20,   # left
        r=20,   # right
        t=40,   # top
        b=20    # bottom
    )
)

HTML(fig.to_html(full_html=False, include_plotlyjs="cdn", auto_play=False))
```
