
# Advanced Customisation

## Priority Icons

One of the most useful things we can do now we've switched to the three-step animation is to apply custom icons to patients with different priorities.

This allows us to better see how they behave in our models.


## A note - VidigiStore vs VidigiPriorityStore

Just like `simpy.Resource` and `simpy.PriorityResource`, we have their analogues `VidigiStore` and `VidigiPriorityStore`.

So for an animation that uses priority, we'd have

::: {.codewindow .python}
g_three_step_animation_custom_priority_icons.py
```{.python}
from vidigi.resources import VidigiPriorityStore
```
:::

And, imagining we have a single priority resource, we'd set it up like this:

::: {.codewindow .python}
g_three_step_animation_custom_priority_icons.py
```{.python}
class Model:
    def __init__(self, param, replication_id):
        ...
        self.nurse = VidigiPriorityStore(self.env, num_resources=self.param.num_nurses)
```
:::

## Requesting a resource with priority

This line is completely unchanged from when we're using a Simpy PriorityResource.

```{.python}
with self.nurse.request(priority=patient.priority) as req:
    ...
```

## Recording priority in our event logs

::: {style='font-size: 75%;'}
Every vidigi logging step can record any number of additional things about an entity, so we can add an entity's priority.

:::

::: {.codewindow .python}
g_three_step_animation_custom_priority_icons.py
```{.python code-line-style="focus:1,dim:2,focus:3,dim:4,focus:5,dim:6-8,focus:9,dim:10,focus:11,dim:12-13,focus:14,dim:15-18,focus:19,dim:20-21,focus:22,dim:23-27,focus:28,dim:29-30,focus:31,dim:32-33,focus:34" code-line-style-preset="emphasis"}
class Model:
    ...
    def attend_clinic(self, patient):
        patient.arrival_time = self.env.now
        self.logger.log_arrival(entity_id=patient.id, priority=patient.priority)

        start_q_nurse = self.env.now

        self.logger.log_queue(
            entity_id=patient.id, event="nurse_wait_begins",
            priority=patient.priority
        )

        with self.nurse.request(priority=patient.priority) as req:
            nurse_obtained = yield req
            end_q_nurse = self.env.now
            patient.q_time_nurse = end_q_nurse - start_q_nurse

            self.logger.log_resource_use_start(
                entity_id=patient.id, event="being_seen_by_nurse",
                resource_id=nurse_obtained.id_attribute,
                priority=patient.priority,
            )

            sampled_nurse_act_time = self.nurse_consult_time_dist.sample()
            yield self.env.timeout(sampled_nurse_act_time)

            self.logger.log_resource_use_end(
                entity_id=patient.id, event="nurse_treatment_ends",
                resource_id=nurse_obtained.id_attribute,
                priority=patient.priority,
            )

        self.logger.log_departure(entity_id=patient.id, priority=patient.priority)
```
:::


## EventLog with priority recorded

Let's now take a quick look at our event log. We can see that it now has a priority column!

```{python}
#| eval: true
#| echo: false
#| label: priority-model-display-event-log

import itables
import pandas as pd
from IPython.display import HTML
itables.init_notebook_mode(all_interactive=True)
itables.options.lengthMenu = [10]
itables.options.layout["topStart"] = None
display(HTML("<style>.dt-container { font-size: 20pt; }</style>"))

from sample_code.g_three_step_animation_custom_priority_icons import Param, Model, Animation
from vidigi.animation import animate_activity_log

my_params = Param(num_nurses=2,
    patient_iat_csv="../sample_code/nspp_example_dataset.csv",
    num_nurses_unav=0,  # Switch off nurse obstruction for this example
    warm_up_period=0
    )
my_model = Model(my_params, replication_id=1)
my_model.run_model()

my_event_log = my_model.get_vidigi_event_log()

my_animation = Animation(my_event_log, my_params)

my_event_log
```


## Animating

Now, if we just run the three step animation as-is, we won't see any impact of the priority resource unless we watch very closely...

```{python}
#| eval: true
#| echo: false
#| label: non-priority-icon-demo-animation

from vidigi.prep import reshape_for_animations, generate_animation_df
from vidigi.animation import generate_animation

reshaped_df = reshape_for_animations(
    event_log=my_event_log,
    every_x_time_units=1,
    limit_duration=my_params.sim_duration,
)

animation_df = generate_animation_df(
    full_entity_df=reshaped_df,
    event_position_df=my_animation.layout,
)

fig = generate_animation(
    full_entity_df_plus_pos=animation_df,
    event_position_df=my_animation.layout,
    scenario=my_params,
)


HTML(fig.to_html(full_html=False, include_plotlyjs="cdn", auto_play=False))
```


## Creating a custom function for assigning icons

We are going to create a new method in our Animation class.

::: {.codewindow .python}
g_three_step_animation_custom_priority_icons.py
```{.python}
class Animation:
    ...

    def show_priority_icon(self, row):
        # First check this isn't a '+ y more' row
        if "more" not in row["icon"]:
            if row["priority"] == 1:
                return "🚨"
            if row["priority"] == 2:
                return "⚠️"
            else:
                return row["icon"]
        else:
            return row["icon"]
```
:::

## Applying our custom function

::: {.codewindow .python}
g_three_step_animation_custom_priority_icons.py
```{.python code-line-style="focus:1,dim:2-3,focus:4,dim:5-14,focus:15-17,dim:18-23" code-line-style-preset="emphasis"}
class Animation:
    ...

    def build_animation(self, time_interval=1):
        reshaped_df = reshape_for_animations(
            event_log=self.event_log,
            every_x_time_units=time_interval,
            limit_duration=self.params.sim_duration
        )

        animation_df = generate_animation_df(
            full_entity_df=reshaped_df,
            event_position_df=self.layout
        )

        animation_df = animation_df.assign(
            icon=animation_df.apply(self.show_priority_icon, axis=1)
        )

        return generate_animation(
            full_entity_df_plus_pos=animation_df,
            event_position_df=self.layout,
            scenario=self.params
        )
```
:::

## Rerunning the animation

And now we can properly see why certain people are jumping the queue!

```{python}
#| eval: true
#| echo: false
#| label: priority-icon-demo-animation

fig = animate_activity_log(
    event_log=my_animation.event_log,
    event_position_df=my_animation.layout,
    every_x_time_units=1,
    plotly_height=500,
    plotly_width=1180
)

HTML(fig.to_html(full_html=False, include_plotlyjs="cdn", auto_play=False))
```
