# Your First Vidigi Animation - a Walkthrough

## New Imports

First, we need a few new imports at the top of our file.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-3,focus:4-6" code-line-style-preset="emphasis"}
import simpy
from sim_tools.distributions import Exponential, Lognormal
import pandas as pd
from vidigi.logging import EventLogger  # NEW
from vidigi.utils import create_event_position_df, EventPosition  # NEW
from vidigi.animation import animate_activity_log  # NEW
```
:::

## Adding a Logging Class

The first thing we need to do is set up our logging class.

We will add this when initialising our `Model` class.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-15,focus:16" code-line-style-preset="emphasis"}
class Model:
    def __init__(self, param):
        self.param = param
        self.env = simpy.Environment()
        self.patient_counter = 0
        self.nurse = simpy.Resource(self.env, capacity=self.param.num_nurses)
        self.patient_inter_dist = Exponential(mean=self.param.mean_patient_inter)
        self.nurse_consult_time_dist = Lognormal(
            mean=self.param.mean_nurse_consult_time,
            stdev=self.param.sd_nurse_consult_time,
        )
        self.list_of_patients = []
        self.mean_q_time_nurse = pd.NA
        self.sd_q_time_nurse = pd.NA
        self.perc_90_q_time_nurse = pd.NA
        self.logger = EventLogger(env=self.env)  # NEW
```
:::

## Adding Logging Steps - Arrivals

We can now access our logger where we need it by calling `self.logger`.

We will place all of the logging steps in the `.attend_clinic()` method.

Let's first add an arrival logging step!

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1,focus:2" code-line-style-preset="emphasis"}
def attend_clinic(self, patient):
    self.logger.log_arrival(entity_id=patient.id)  # NEW
```
:::

::: {style='font-size: 80%;'}
Because we already gave our logger access to the SimPy env, it handles recording the time the event happened! So the only parameter we need to give our logger is an identifier for this patient, which they already record.

:::


## Adding Logging Steps - Queuing

We now record a **queuing** step with `.log_queue()`

This time, we also need to decide on a name for our event. This can be anything we like, though it's good practice to use `snake_case` (i.e. lowercase with underscores instead of spaces).

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-5,focus:6,dim:7-11" code-line-style-preset="emphasis"}
def attend_clinic(self, patient):
    self.logger.log_arrival(entity_id=patient.id)

    start_q_nurse = self.env.now

    self.logger.log_queue(entity_id=patient.id, event="nurse_wait_begins")  # NEW

    with self.nurse.request() as req:
        yield req
        end_q_nurse = self.env.now
        ...
```
:::

## The simple way to record activity use

We're going to start with the simplest way of logging that someone is being seen by the nurse - also treating it as a `queue` in vidigi's language.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-7,focus:8,dim:9-12,focus:13" code-line-style-preset="emphasis"}
def attend_clinic(self, patient):
    ...
    with self.nurse.request() as req:
        yield req
        end_q_nurse = self.env.now
        patient.q_time_nurse = end_q_nurse - start_q_nurse

        self.logger.log_queue(entity_id=patient.id, event="being_seen_by_nurse")  # NEW

        sampled_nurse_act_time = self.nurse_consult_time_dist.sample()
        yield self.env.timeout(sampled_nurse_act_time)

        self.logger.log_queue(entity_id=patient.id, event="nurse_treatment_ends")  # NEW
```
:::

## But it's not a queue?!

Later, we'll look at vidigi's more advanced ways of tracking resource use, but treating it as a 'queue' step for now allows us to get a simple animation up and running very quickly.

## Adding Logging Steps - Departure

Finally, every patient needs one departure event.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1,focus:2" code-line-style-preset="emphasis"}
def attend_clinic(self, patient):
    self.logger.log_arrival(entity_id=patient.id)  # NEW
```
:::

<br>

::: {.value-box icon="fa-solid fa-triangle-exclamation" icon-position="left" color="bg-red"}
It's important that each patient only has **one** arrival and **one** departure event per model run.

Things get messy if they don't!

(So if there's any way they can 'leave and come back' in your model, think carefully about how you'll handle it...)
:::


## All the logging steps

Let's recap the changes we made.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1,focus:2,dim:3-5,focus:6,dim:7-12,focus:13,dim:14-17,focus:18,dim:19,focus:20" code-line-style-preset="emphasis"}
def attend_clinic(self, patient):
    self.logger.log_arrival(entity_id=patient.id)  # NEW

    start_q_nurse = self.env.now

    self.logger.log_queue(entity_id=patient.id, event="nurse_wait_begins")  # NEW

    with self.nurse.request() as req:
        yield req
        end_q_nurse = self.env.now
        patient.q_time_nurse = end_q_nurse - start_q_nurse

        self.logger.log_queue(entity_id=patient.id, event="being_seen_by_nurse")  # NEW

        sampled_nurse_act_time = self.nurse_consult_time_dist.sample()
        yield self.env.timeout(sampled_nurse_act_time)

        self.logger.log_queue(entity_id=patient.id, event="nurse_treatment_ends")  # NEW

    self.logger.log_departure(entity_id=patient.id)  # NEW
```
:::

## Accessing our event log

We'll want to grab out our event log as a pandas dataframe.

It's neat to set up a little helper method in our `Model` class to do that.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python}
def get_vidigi_event_log(self):
    return self.logger.to_dataframe()
```
:::

Vidigi provides the `to_dataframe()` method for our convenience. This will look at the EventLogger object, find where it stores the event logs, and convert it into this format for us.

## The new class - Animation

Our models contain some key classes: `Params`, `Patient`, `Model`

(also `Trial`, but in this first example, we're just working at the level of a single model - we'll look at wiring Vidigi into `Trial` a bit later)

We're now going to define a brand new class called `Animation`.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python}
class Animation:
    def __init__(self, params, event_log):
        self.params = params
        self.event_log = event_log
```
:::

## Setting up a Layout Grid

The next thing we'll define - still in our init method - is a layout grid.

:::: {.columns}

::: {.column width='40%'}
::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python}
EventPosition(
    event="nurse_wait_begins",
    x=200,
    y=250,
    label="Waiting for Nurse"
    )
```
:::
:::

::: {.column width='5%'}
:::

::: {.column width='55%' style="font-size: 75%;"}

For each event we want in our animation, we create an `EventPosition` object and pass four things:

- the event name (which should match what we called it in the logger)
- an x coordinate for the front of that queue
- a y coordinate for the front of that queue
- a nicer label to use in the animation

:::

::::





## Coordinates

[TODO: create a blank axis]

[TODO: grab full fig from vidigi paper]

## Arrival and Departure Events

Behind the scenes, EventLogger always gives these the same event name if you use `.log_arrival()` and `.log_departure()`.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python}
EventPosition(
    event="arrival", x=0, y=350, label="Entrance"
)
```
:::

<br>

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python}
EventPosition(
    event="depart", x=200, y=50, label="Exit"
)
```
:::

## `create_event_position_df`

::: {style="font-size: 65%;"}

We pass a `list` of all our EventPosition objects to the function `create_event_position_df`.
Remember - a Python list uses `[]` with each item separated by a `,`
:::

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python}
create_event_position_df(
    [
        EventPosition(
            event="arrival", x=0, y=350, label="Entrance"
        ),
        EventPosition(
            event="nurse_wait_begins", x=200, y=250, label="Waiting for Nurse"
        ),
        EventPosition(
            event="being_seen_by_nurse", x=200, y=150, label="Being Seen By Nurse"
        ),
        EventPosition(
            event="depart", x=200, y=50, label="Exit"
        )
    ]
)
```
:::

::: {style="font-size: 65%;"}
::: {.fragment}
We don't need to visualise the 'nurse_treatment_ends' step as the timing will be identical to the depart step.
:::
:::


## The full Grid in situ

We'll bind this to `self.layout`.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-5,focus:6-23" code-line-style-preset="emphasis"}
class Animation:
    def __init__(self, event_log):
        self.event_log = event_log

        self.layout = create_event_position_df(
            [
                EventPosition(
                    event="arrival", x=0, y=350, label="Entrance"
                ),
                EventPosition(
                    event="nurse_wait_begins", x=200, y=250, label="Waiting for Nurse"
                ),
                EventPosition(
                    event="being_seen_by_nurse", x=200, y=150, label="Being Seen By Nurse"
                ),
                # We don't need to visualise the 'nurse_treatment_ends' step
                # as the timing will be identical to the depart step
                EventPosition(
                    event="depart", x=200, y=50, label="Exit"
                )
            ]
        )
```
:::

## Generating the Animation

Now, we just need a small function to call vidigi's animation creation logic.

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-4,focus:5-11" code-line-style-preset="emphasis"}
class Animation:
    def __init__(self, event_log):
        ...

    def build_animation(self, time_interval=1):
        return animate_activity_log(
            event_log=self.event_log,
            event_position_df=self.layout,
            every_x_time_units=time_interval,
        )
```
:::

## Calling the animation

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-7,focus:8-11" code-line-style-preset="emphasis"}
my_params = Param()
my_model = Model(my_params)
my_model.run_model()

patient_df = my_model.convert_entity_list_to_dataframe(my_model.list_of_patients)
my_model.calculate_run_results(patient_df)

my_event_log = my_model.get_vidigi_event_log()

my_animation = Animation(my_event_log)
my_animation.build_animation()
```
:::

## The event log

```{python}
#| eval: true
#| echo: false

import itables
import pandas as pd
from IPython.display import HTML
itables.init_notebook_mode(all_interactive=True)
itables.options.lengthMenu = [10]
itables.options.layout["topStart"] = None
display(HTML("<style>.dt-container { font-size: 20pt; }</style>"))

df = pd.read_csv("resources/simple_event_log_output.csv")

df
```


## The animation

```{python}
#| eval: true
#| echo: false

from sample_code.b_simple_one_step_model_vidigi import Param, Model, Animation
from vidigi.animation import animate_activity_log

my_params = Param()
my_model = Model(my_params)
my_model.run_model()

my_event_log = my_model.get_vidigi_event_log()
my_animation = Animation(my_event_log)

fig = animate_activity_log(
    event_log=my_animation.event_log,
    event_position_df=my_animation.layout,
    every_x_time_units=1,
    plotly_height=600,
    plotly_width=1180
)

HTML(fig.to_html(full_html=False, include_plotlyjs="cdn"))
```



## BONUS: `if __name__ == 'main'`

If you head to the folder in sample_code, you may notice a funny line:

::: {.codewindow .python}
b_simple_one_step_model_vidigi.py
```{.python code-line-style="dim:1-8,focus:9,dim:10-13" code-line-style-preset="emphasis"}
class Animation:
    def __init__(self, event_log):
        ...

    def build_animation(self, time_interval=1):
        return animate_activity_log(event_log=self.event_log,
            event_position_df=self.layout, every_x_time_units=time_interval)

if __name__ == "__main__":
    my_params = Param()
    my_model = Model(my_params)
    my_model.run_model()
    ...
```
:::

## BONUS: `if __name__ == 'main'` - explanation

`if __name__ == 'main':` simply means [**'only run the code in this block if you are running the original file'**]{style="color:yellow"}

When you run the file (script) in the terminal or the interactive window, the code in this block will run (execute).

::: {.fragment}
HOWEVER, if you import pieces of that code into another file, it *won't* run the bit in the `if __name__ == 'main':` block.
:::


::: {.value-box fragment="fade-in" icon="fa-solid fa-lightbulb" icon-position="left" align="center" color="bg-green"}
This is really useful if we want to reuse our classes somewhere else, like in a web app, so we'll be getting in the habit of doing this.
:::
