# Additional customisation for your vidigi animations

## Why customise?

::: {.focus-list}
- Vidigi animations often require a little bit of tweaking to look their best
- Other parameters can help you find a balance between the granularity of the animation and the time it takes to regenerate
:::

## Time Interval

For this, vidigi thinks in time 'units'.

If your model is set up in minutes, 1 unit = 1 minute

If it's set in weeks, 1 unit = 1 week

```{.python code-line-style="focus:1,dim:2-3,focus:4,dim:5" code-line-style-preset="emphasis"}
animate_activity_log(
    event_log=event_log,
    event_position_df=layout,
    every_x_time_units=1,
)
```


::: {.fragment}
Why not always just use a time unit of 1?

The time interval has a big impact on the time it takes for an animation to generate.

It directly influences how big the underlying dataframe is, as well as the number of frames of animation data that need to be stored.
:::



## Every 1 minute

```{python}
#| eval: true
#| echo: false
#| label: every-1-min-time-size

from sample_code.b_simple_one_step_model_vidigi import Param, Model, Animation
from vidigi.animation import animate_activity_log
import time


my_params = Param(sim_duration=60*24)
my_model = Model(my_params)
my_model.run_model()

my_event_log = my_model.get_vidigi_event_log()
my_animation = Animation(my_event_log)

# Time the animation generation
start_time_1 = time.perf_counter()

fig = animate_activity_log(
    event_log=my_animation.event_log,
    event_position_df=my_animation.layout,
    every_x_time_units=1,
    plotly_height=600,
    plotly_width=1000
)

animation_time_1 = time.perf_counter() - start_time_1

html_fig_1 = fig.to_html(full_html=False, include_plotlyjs="cdn")

size_kb_1 = len(html_fig_1.encode("utf-8")) / 1024

HTML(html_fig_1)
```


## Every 10 minutes

```{python}
#| eval: true
#| echo: false
#| label: every-10-mins-time-size
start_time_2 = time.perf_counter()

fig = animate_activity_log(
    event_log=my_animation.event_log,
    event_position_df=my_animation.layout,
    every_x_time_units=10,
    plotly_height=600,
    plotly_width=1000
)

animation_time_2 = time.perf_counter() - start_time_2

html_fig_2 = fig.to_html(full_html=False, include_plotlyjs="cdn")

size_kb_2 = len(html_fig_2.encode("utf-8")) / 1024

HTML(html_fig_2)
```


## Time Interval - A Comparison

Let's compare some figures for an animation that runs for 24 hours of a clinic.

:::: {.columns}

::: {.column width='50%'}

**Every 1 minute**

- Total frames:  `{python} round(my_params.sim_duration / 1, 0)`
- Time to generate:  `{python} round(animation_time_1,2)` seconds
- Animation file size:  `{python} round(size_kb_1,1)` kb

:::

::: {.column width='50%'}
**Every 10 minutes**

- Total frames:  `{python} round(my_params.sim_duration / 10,0)`
- Time to generate:  `{python} round(animation_time_2,2)` seconds
- Animation file size:  `{python} round(size_kb_2,1)` kb

:::

::::




## Play Speed

## Queue Wrapping

## Entity Spacing

##
