# Exercise 1

## {.slide data-menu-title="Vidigi Exercise 1"}

:::: {.columns}

::: {.column width='60%'}
::: {style='font-size: 75%;'}
You will be working with the file `exercises/exercise_1.py`, which contains a model that .
:::
:::

::: {.column width='30%'}
::: {.value-box icon="fa-solid fa-clock" icon-position="left" icon-size="2em" min-height="60px" font-size="0.8rem"}
45 minutes <br>+ 10 minute break
:::
:::

::::


:::: {.columns}

::: {.column width='60%'}
::: {style='font-size: 85%'}
#### Part A
1. Add a logger
1. Add the required logging steps
    - arrival
    - queues [(I'd recommend just using queues, not resource use, to start with)]{style="color:lightgrey;font-size: 65%"}
    - departure
1. Add a method to get the event log from your Model as a dataframe
1. Print the first 20 rows of your event log
1. Set up and generate the animation
    - [you have been provided with a starter template for the layout]{style="color:lightgrey;font-size: 65%"}

#### Part B

1. Go back through and convert appropriate queues to resource use
:::
:::



::: {.column width='40%'}
::: {.fragment}
::: {style='font-size: 70%; color: lightgrey'}
### Extensions

- Try increasing the arrival rate [TODO: To x]. Does the animation still look ok? Does it take longer to generate?
- Try changing the number of resources.
- Try tweaking the EventPositions. Do you think a different layout might look better?
- Try out the parameters `custom_entity_icon_list`, `custom_resource_icon`, choosing some emojis from [emojipedia.org](https://emojipedia.org/)
:::
:::
:::

::::
